---
- hosts: localhost
  gather_facts: no

  vars:
    project_dir: "serasa-experian/DevSecOps/aws-service-s3" # folder that contains main.tf, ...

  tasks:
    - name: Run terraform
      community.general.terraform:
        project_path: '{{ project_dir }}'
        state: present
        variables: 
          
      register: output

    - debug:
        var: output
