---
- hosts: localhost
  connection: local
  gather_facts: no

  vars:
    project_dir: "DevSecOps/aws-service-s3" # folder that contains main.tf, ...

  tasks:
    - name: Run terraform
      community.general.terraform:
        project_path: '{{ project_dir }}'
        state: present
        variables: 
          name: "{{ s3_name }}}"
          region: "{{ aws_region }}"
          stage: "{{ aws_env }}"
          
      register: output

    - debug:
        var: output
