AWSTemplateFormatVersion: 2010-09-09
Description: Create role for BU to perform assume role to Service Catalog.
 
Parameters:
  WorkerJoaquinAccount:
    Description: Account to grant specific Service Catalog access.
    Type: String
    Default: "707064604759"
 
Resources:
  BURoleForDevSecOpsCockpitService:
    Type: AWS::IAM::Role
    Properties:
      RoleName: BURoleForDevSecOpsCockpitService
      MaxSessionDuration: 43200
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Sub "arn:aws:iam::${WorkerJoaquinAccount}:role/BURoleForDevSecOpsCockpitService"
            Action:
              - sts:AssumeRole
      Path: /
 
  BUPolicyForUseDevSecOpsServiceCatalog:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: BUPolicyForUseDevSecOpsServiceCatalog
      Roles:
        - !Ref 'BURoleForDevSecOpsCockpitService'
      PolicyDocument:
        Version: 2012-10-17
        Statement:
            - Sid: CatalogPolicy
              Effect: Allow
              Action:
                - 'ec2:*'
                - 'elasticloadbalancing:*'
                - 'elasticfilesystem:*'
                - 'cloudwatch:*'
                - 'autoscaling:*'
                - 'iam:*'
                - 'acm:*'
                - 'organizations:*'
                - 'kms:*'
                - 's3:*'
                - 'rds:*'
                - 'eks:*'
                - 'logs:*'
                - 'dynamodb:*'
                - 'cassandra:*'
                - 'ecr:*'
                - 'sqs:*'
                - 'airflow:*'
                - 'route53:*'
              Resource: '*'

