##NAO ALTERAR!!!!!!######
#Role for ALL
- hosts: spobrcatalog
  become: true
  environment: "{{ proxy_env }}"
  vars_files:
    - ans-shared-vars/aws-@@AWS_ACCOUNT_ID@@-env.yml
    - ans-shared-vars/lnx-credentials-env.yml
    - ans-shared-vars/pwd-credentials.yml
    - ans-shared-vars/lnx-proxy-env.yml
    #####
##FIM NAO ALTERAR!!!!!!######
  roles:
    - aws-replace

     