---
- name: Disable proxy if configured
  shell: unset http_proxy

#- name: Get description
#  shell: awk -F ":" '{print $2}' /usr/scripts/descricao.txt
#  register: tag_server
#  ignore_errors: yes
#
#- name: Define default permission to /var/log
#  file:
#    path: /var/log
#    state: directory
#    mode: 0755
    
- name: Uninstall Zabbix Agent Old
  yum:
    name: '{{item}}'
    state: absent
  with_items:
    - zabbix-agent2
    - zabbix-agent

- name: Install Zabbix Agent2 EC2-Linux when Version 2 current is {{ansible_distribution_major_version}}
  yum:
    name: https://repo.zabbix.com/zabbix/6.0/rhel/7/x86_64/zabbix-agent2-6.0.0-1.el7.x86_64.rpm
    state: present
  when: ansible_distribution_major_version|int == 2 or ansible_distribution_major_version|int >= 7

- name: Zabbix_proxy
  import_tasks: set_zabbix_proxy.yml

- name: Copy Zabbix Agent config
  template:
    src: zabbix_agent2.conf
    dest: /etc/zabbix
    owner: root
    group: root
    mode: 0644

- name: Enable and start Zabbix Agent2
  service:
    name: zabbix-agent2
    enabled: yes
    state: restarted


##Utilizado para a task de acls que vem na sequencia
#- set_fact:
#    filepath: /var/log/messages
#
#- import_role:
#    name: acl
#    tasks_from: acl_set_zabbix_log_file
  tags:
    - setzabbix
