- name: add User to system
  user:
    name: "{{ ssh_username }}"

- name: Set authorized key took from file
  authorized_key:
    user: "{{ ssh_username }}"
    state: present
    key: "{{ lookup('file', 'files/public_keys/jenkins_id_rsa.pub') }}"

- name: sudo without password for user
  copy:
    content: '{{ ssh_username }} ALL=(ALL:ALL) NOPASSWD:ALL'
    dest: /etc/sudoers.d/{{ ssh_username }}
    mode: 0440