apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollout-istio
  namespace: deploy-system
  annotations:
    argocd.argoproj.io/manifest-generate-paths: ..
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: app/rollouts-demo/examples/istio/
    repoURL: ssh://git@code.experian.local/cdeamlo/coe-argocd.git
    targetRevision: develop/COMLDE-1160
  destination:
    namespace: rollouts-demo-istio
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
