---
app_host_name: prometheus_elastic
app_host_ip: K8S_URL
app_host_port: 30090
app_host_vhost: "spobr{{bu_name}}prometheus{{ env_stack }}{{ domain }}"
ldap_system_user: "{{ ldap_user_serasa }}"
ldap_system_password: "{{ ldap_password_serasa }}"
ldap: false