apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-virtual-service
  {{- if .Values.annotations }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "airflow.labels" . | nindent 4 }}
    component: istio
    {{- if .Values.labels }}
    {{- toYaml .Values.labels | nindent 4 }}
    {{- end }}
spec:
  hosts:
    {{- if .Values.host }}
      - {{ .Values.host }}
    {{- end }}
      - {{ include "default.host" . }}
  gateways:
  - {{ .Release.Name }}-gateway
  http:
  - route:
    - destination:
        host: {{ .Release.Name }}-webserver
        port:
          number: 8080
      headers:
        request:
          set:
            X-Forwarded-Proto: https