apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Release.Name }}-gateway
  {{- if .Values.annotations }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "airflow.labels" . | nindent 4 }}
    component: istio
    {{- if .Values.labels }}
    {{- toYaml .Values.labels | nindent 4 }}
    {{- end }}
spec:
  selector:
    istio: ingress
  servers:
  - port:
      number: 8080
      name: http
      protocol: HTTP
    hosts:
    {{- if .Values.host }}
      - {{ .Values.host }}
    {{- end }}
      - {{ include "default.host" . }}
      

