apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: airflow-secrets-configs-spc
  {{- if .Values.annotations }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "airflow.labels" . | nindent 4 }}
    component: awssecretmanager
    {{- if .Values.labels }}
    {{- toYaml .Values.labels | nindent 4 }}
    {{- end }}
spec:
  provider: aws
  parameters:
    objects: |
        - objectName: {{ include "secretmanager.datasource" . }}
          objectType: "secretsmanager"
          jmesPath:
            - path: db_url
              objectAlias: dbURL
        - objectName: {{ include "secretmanager.websecretkey" . }}
          objectType: "secretsmanager"
          jmesPath:
            - path: secret_key
              objectAlias: webserverSecretKey
        - objectName: {{ include "secretmanager.gitsshprivkey" . }}
          objectType: "secretsmanager"
          objectAlias: gitSSHToken        
  # Create k8s secret. It requires volume mount first in the pod and then sync.
  secretObjects:
    - secretName: mlops-airflow-db-url
      type: Opaque
      data:
        - objectName: dbURL
          key: connection
    - secretName: mlops-airflow-webserver-secretkey
      type: Opaque
      data:
        - objectName: webserverSecretKey
          key: webserver-secret-key
    - secretName: mlops-airflow-ssh-secret
      type: Opaque
      data:
        - objectName: gitSSHToken
          key: gitSshKey
