apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: airflow-fernetkey-spc
  {{- if .Values.annotations }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "airflow.labels" . | nindent 4 }}
    component: awssecretmanager
    {{- if .Values.labels }}
    {{- toYaml .Values.labels | nindent 4 }}
    {{- end }}
spec:
  provider: aws
  parameters:
    objects: |
        - objectName: {{ include "secretmanager.fernetkey" . }}
          objectType: "secretsmanager"
          jmesPath:
            - path: fernet_key
              objectAlias: airflowFernetKey         
  # Create k8s secret. It requires volume mount first in the pod and then sync.
  secretObjects:
    - secretName: mlops-airflow-fernetkey
      type: Opaque
      data:
        - objectName: airflowFernetKey
          key: fernet-key
