apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: mlops-airflow-webconfig-spc
  {{- if .Values.annotations }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "airflow.labels" . | nindent 4 }}
    component: awssecretmanager
    {{- if .Values.labels }}
    {{- toYaml .Values.labels | nindent 4 }}
    {{- end }}
spec:
  provider: aws
  parameters:
    objects: |
        - objectName: "{{ include "secretmanager.webserverconfig" . }}"
          objectType: "secretsmanager"
          objectAlias: "webserver_config.py"
  # Create k8s secret. It requires volume mount first in the pod and then sync.
  secretObjects:
    - secretName: mlops-airflow-webserver-config
      type: Opaque
      data:
      - key: webserver_config.py
        objectName: webserver_config.py      



