{{ if .Values.service_account.create  }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.service_account.name }}
  annotations:
  {{- with .Values.service_account.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.annotations }}
    {{- toYaml .Values.annotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "airflow.labels" . | nindent 4 }}
    component: serviceaccount
    {{- if .Values.labels }}
    {{- toYaml .Values.labels | nindent 4 }}
    {{- end }}
{{ end }}