apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mlops-airflow-sm
  {{- if .Values.annotations }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "airflow.labels" . | nindent 4 }}
    component: monitoring
    release: monitoring-system
    {{- if .Values.labels }}
    {{- toYaml .Values.labels | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      component: statsd
      release: {{ .Release.Name }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  endpoints:
    - port: statsd-scrape
      interval: 15s