apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: model-hdm2-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: ..
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    path: helm
    repoURL: https://bb-drone-poc.dev-mlops.br.experian.eeca/scm/drag/model-hdm2-infra.git
    targetRevision: main
    helm:
      valueFiles:
        - values-main.yaml

  destination:
    namespace: model-hdm2-prod
    server: https://kubernetes.default.svc
  
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true