---
- name: list security groups from {{account}} account
  shell: '/usr/local/bin/aws ec2 describe-security-groups --query "SecurityGroups[*].{Name:GroupName,ID:GroupId}" --region {{account_region}}  --profile=sts_cli'
  register: sg_list

- debug:
    var: sg_list.stdout_lines

    ###SDG###    
