---
- name: get instance information by id {{instance_id}}
  environment:
    https_proxy: 'http://spobrproxy.serasa.intranet:3128'
    http_proxy: 'http://spobrproxy.serasa.intranet:3128'
    AWS_ACCESS_KEY_ID: "{{ak}}"
    AWS_SECRET_ACCESS_KEY: "{{sk}}"
  shell: aws ec2 describe-instances --instance-ids '{{instance_id}}'  --output text
  #  shell: aws ec2 describe-instances --instance-ids '{{instance_id}}' --query 'Reservations[*].Instances[*].{ip:PrivateIpAddress}' --output text
  args:
    executable: /bin/bash
  register: result_instance_id

- debug:
    var: result_instance_id
