---
- name: clean actual config
  shell: '{{item}}'
  ignore_errors: yes
  with_items:
    - "/usr/local/bin/aws iam detach-role-policy --role-name BURoleForSREAutomation --policy-arn arn:aws:iam::{{account_id}}:policy/BUPolicyForSREAutomation --profile={{account}}"
    - "/usr/local/bin/aws iam delete-policy --policy-arn arn:aws:iam::{{account_id}}:policy/BUPolicyForSREAutomation --profile={{account}}"
    - "/usr/local/bin/aws iam delete-role --role-name BURoleForSREAutomation --profile={{account}}"  



- name: create role BURoleForSREAutomation from  profile {{account}} account_id {{account_id}}
  shell: "/usr/local/bin/aws --profile={{account}} iam create-role --role-name BURoleForSREAutomation --assume-role-policy-document file://roles/aws/files/BURoleForSREAutomation.json"  
  ignore_errors: yes
  register: role_created

- debug:
    var: role_created  




- name: create policy BUPolicyForSREAutomation from  profile {{account}} account_id {{account_id}}
  shell: "/usr/local/bin/aws --profile={{account}} iam create-policy --policy-name BUPolicyForSREAutomation --policy-document file://roles/aws/files/BUPolicyForSREAutomation.json"
  ignore_errors: yes
  register: policy_created

- debug:
    var: policy_created  

- name: Attach Policy BUPolicyForSREAutomation in Role BURoleForSREAutomation  from profile {{account}} account_id {{account_id}}
  shell:  "/usr/local/bin/aws --profile={{account}} iam attach-role-policy --policy-arn arn:aws:iam::{{account_id}}:policy/BUPolicyForSREAutomation --role-name BURoleForSREAutomation"
  ignore_errors: yes
  register: policy_attached

- debug:
    var: policy_attached
  
    ###SDG##


