---
- name: include task to set assume role
  include_tasks: sts_connection.yml


- name: Add {{secret_name}} to AWS Secrets Manager in account {{account_name}}
  community.aws.secretsmanager_secret:
    aws_access_key: "{{ assumed_role_ak }}"
    aws_secret_key: "{{ assumed_role_sk }}"
    security_token: "{{ assumed_role_token }}"
    region: '{{account_region}}'
    validate_certs: no

    name: '{{secret_name}}'
    state: present
    secret_type: 'string'
    secret: "{{secret_string}}"        
    overwrite: false
  register: registred_secret

- debug:
    msg: 
      - "##############################"
      - "###### Secret Registred ######"
      - "##############################"
      - "{{registred_secret.secret}}"
      - "##############################"
      - "##############################"
  when: registred_secret is defined
