---
# defaults file for cassandra
#cassandra_url: "https://archive.apache.org/dist/cassandra/redhat/40x/cassandra-{{cassandra_release}}.rpm"
cassandra_url: "https://archive.apache.org/dist/cassandra/redhat"
cassandra_version_base: "40x"
cassandra_release: "4.0.4-1.noarch"

cassandra_cluster_name: ""
cassandra_seeds: []

cassandra_num_tokens: 256
cassandra_allocate_tokens_for_local_replication_factor: 3
cassandra_hinted_handoff_enabled: true
cassandra_topology_class: "NetworkTopologyStrategy"
cassandra_topology_datacenter_name: "datacenter1"
cassandra_endpoint_snitch: "SimpleSnitch"

cassandra_topology: []

cassandra_disk_failure_policy: "stop"
cassandra_commit_failure_policy: "stop"
cassandra_base_directory: "/data"
cassandra_data_base_directory: "/cassandra-data"
cassandra_saved_caches_directory: "/saved_caches"
cassandra_hints_directory_directory: "/hints"
cassandra_commitlog_directory: "/cassandra-commitlog/"
cassandra_log_directory: "/cassandra-log"

cassandra_data_file_directories:
  - /cassandra-data

cassandra_partitioner: "Murmur3Partitioner"
cassandra_config_dir_base: "/etc/cassandra/conf"
cassandra_disk_queue_scheduler: "deadline"

cassandra_jvm_xms: "16G"
cassandra_jvm_xmx: "16G"

cqlsh_version: 6.0.0
initial_token: {}
