apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: {{ include "dex.fullname" . }}-config
spec:
  provider: aws
  secretObjects:
    - secretName:  {{ include "dex.fullname" . }}-config
  parameters:
    objects: |
      - objectName: "{{ .Values.secretsManager}}"
        objectType: "secretsmanager"
        objectAlias: "config.yaml"