apiVersion: v1
kind: Service
metadata:
  name: tracing
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "jaeger.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: http-query
    port: 80
    protocol: TCP
    targetPort: 16686
  - name: grpc-query
    port: 16685
    protocol: TCP
    targetPort: 16685
  selector:
  {{ include "jaeger.labels" . | indent 4 }}

---

apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "jaeger.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: jaeger-collector-http
    port: 14268
    targetPort: 14268
    protocol: TCP
  - name: jaeger-collector-grpc
    port: 14250
    targetPort: 14250
    protocol: TCP
  - port: 9411
    targetPort: 9411
    name: http-zipkin
  selector:
  {{ include "jaeger.labels" . | indent 4 }}

---

apiVersion: v1
kind: Service
metadata:
  name: zipkin
  namespace: {{ .Release.Namespace }}
  labels:
    name: zipkin
spec:
  type: ClusterIP
  ports:
  - name: http-query
    port: 9411
    protocol: TCP
    targetPort: 9411
  selector:
  {{ include "jaeger.labels" . | indent 4 }}