apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  name: {{ template "rbac.name.system.account" . }}
  namespace: kube-system
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "chart.name" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "chart.name" . }}
  name: {{ template "rbac.name.role" . }}
  namespace: kube-system
rules:
- apiGroups: [""]
  resourceNames:
  - aws-auth
  resources:
  - configmaps
  verbs:
  - list
  - watch
  - update
  - patch
  - get
- apiGroups:
  - apps
  resourceNames:
  - aws-node
  - aws-auth
  resources:
  - daemonsets
  - daemonsets/status
  - configmaps
  verbs:
  - list
  - watch
  - update
  - patch
  - get
- apiGroups:
  - extensions
  resourceNames:
  - aws-node
  - aws-auth
  resources:
  - daemonsets
  - daemonsets/status
  - configmaps
  verbs:
  - list
  - watch
  - update
  - patch
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "chart.name" . }}
  name: {{ template "rbac.name.role.binding" . }}
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "rbac.name.role" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "rbac.name.system.account" . }}
  namespace: kube-system