apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: argocd-repositories
spec:
  provider: aws
  secretObjects:
    - secretName: argocd-repositories
      type: Opaque
      labels:
        argocd.argoproj.io/secret-type: repo-creds
      data:
        - objectName: "url"
          key: url
        - objectName: "sshPrivateKey"
          key: sshPrivateKey
  parameters:
    objects: |
      - objectName: {{ .Values.coe_argocd.secretsManager }}
        objectType: "secretsmanager"
        jmesPath:
            - path: "url"
              objectAlias: "url"
            - path: "sshPrivateKey"
              objectAlias: "sshPrivateKey"
