{{- if .Values.istio.enabled -}}
{{- $fullName := include "dex.fullname" . -}}
{{- $svcPort := .Values.service.ports.http.port -}}
{{- if .Values.istio.gateway.create -}}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{  .Values.istio.gateway.name }}
  labels:
    {{- include "dex.labels" . | nindent 4 }}
  {{- with .Values.istio.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    istio: ingress
  servers:
    - hosts:
      {{- range .Values.istio.hosts }}
        - {{ . | quote }}
      {{- end}}
      port:
        name: {{  .Values.istio.gateway.portName }}
        number: {{  .Values.istio.gateway.portNumber }}
        protocol: {{  .Values.istio.gateway.portProtocol }}

---
{{- end}}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{  .Values.istio.virtualServiceName }}
spec:
  gateways:
    - {{ .Values.istio.gateway.name }}
  hosts:
    {{- range .Values.istio.hosts }}
      - {{ . | quote }}
    {{- end}}
  http:
    - route:
        - destination:
            host: {{ $fullName }}
            port:
              number: {{ $svcPort }}
{{- end }}