apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: dex-config  
spec:
  provider: aws
  secretObjects:
    - secretName: dex-config
  parameters:
    objects: |
      - objectName: "{{ .Values.secretsManager}}"
        objectType: "secretsmanager"
        objectAlias: "config.yaml"