{{- $strategy := .Values.deployment.strategy | default dict }}
{{- $manager := "flagger" }}
{{- if and $strategy $strategy.manager }}
{{- $manager = $strategy.manager }}
{{- end }}
{{- if (ne "argo-rollouts" $manager) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "stateless-app.fullname" . }}
  labels:
    {{- include "stateless-app.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.deployment.production.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "stateless-app.selectorLabels" . | nindent 6 }}
  revisionHistoryLimit: 3
  progressDeadlineSeconds: 600
  strategy:
    {{- with .Values.rollingUpdate }}
    rollingUpdate:
      {{- toYaml . | nindent 6 }}
    {{- end }} 
  template:
    metadata:
      annotations:
        timestamp: {{ now | unixEpoch | quote }}
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "stateless-app.labels" . | nindent 8 }}
        autoscaling: "{{ .Values.autoscaling.enabled }}"
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "stateless-app.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.deployment.repository }}:{{ .Values.deployment.production.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.deployment.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
              protocol: TCP
            {{- if .Values.additionalContainerPorts }}
            {{- range .Values.additionalContainerPorts }}
            - containerPort: {{ . }}
              protocol: TCP
            {{- end }}
            {{- end }}
          {{- with .Values.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}          
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: GEARR_ID
              value: {{ .Values.app.labels.gearr | squote }}
            - name: CLUSTER_NAME
              value: {{ .Values.deployment.cluster }}
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          envFrom:
          	{{- if .Values.secretsRefs }}
            {{- range .Values.secretsRefs }}
            - secretRef:
                name: {{ . }}
            {{- end }}
            {{- end }}
            {{- if .Values.configMapsRefs }}
            {{- range .Values.configMapsRefs }}
            - configMapRef:
                name: {{ . }}
            {{- end }}
            {{- end }}
            {{- if or (.Values.envFile) (.Values.envVars) }}
            - configMapRef:
                name: {{ .Release.Name }}-configmap
            {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
