{{- $apiVersion := .Values.autoscaling.apiVersion | default "v2" }}
{{- if and (.Values.autoscaling.enabled) (eq $apiVersion "v2") }}
{{- $targetApiVersion := "apps/v1" }}
{{- $targetKind := "Deployment" }}
{{- $strategy := .Values.deployment.strategy | default dict }}
{{- if (eq "Canary" $strategy.type) }}
{{- $manager := "flagger" }}
{{- if and $strategy $strategy.manager }}
{{- $manager = $strategy.manager }}
{{- end }}
{{- if (eq "argo-rollouts" $manager) }}
{{- $targetApiVersion = "argoproj.io/v1alpha1" }}
{{- $targetKind = "Rollout" }}
{{- end }}
{{- end }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "stateless-app.fullname" . }}
  labels:
    {{- include "stateless-app.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: {{ $targetApiVersion }}
    kind: {{ $targetKind }}
    name: {{ include "stateless-app.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
