{{- $vsvc := .Values.virtualService | default dict }}
{{- $strategy := .Values.deployment.strategy | default dict }}
{{- if or (not $strategy) (ne "Canary" $strategy.type) }}
{{- if $vsvc.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "stateless-app.fullname" . }}-virtual-service
  labels:
    {{- include "stateless-app.labels" . | nindent 4 }}
spec:
  hosts:
  - "{{ .Values.deployment.host }}"
  gateways:
  - {{ include "stateless-app.fullname" . }}-gateway
  http:
  - name: {{ include "stateless-app.fullname" . }}-route
    {{- with .Values.virtualService.match }}
    match:
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.virtualService.rewrite }}
    rewrite:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    route:
    - destination:
        host: {{ include "stateless-app.fullname" . }}-service
        port: 
          number: {{ .Values.service.port }}
      headers:
        request:
          set:
            X-Forwarded-Proto: https
    {{- with .Values.virtualService.corsPolicy }}
    corsPolicy:
      {{- toYaml . | nindent 6 }}
    {{- end }}
{{- end }}
{{- end }}
