{{- $vsvc := .Values.virtualService | default dict }}
{{- if $vsvc.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "stateless-app.fullname" . }}-gateway
  labels:
    {{- include "stateless-app.labels" . | nindent 4 }}
spec:
  selector:
    istio: ingress
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    tls:
      httpsRedirect: true
    hosts:
    - "{{ .Values.deployment.host }}"
  - port:
      number: 8080
      name: https
      protocol: HTTP
    hosts:
    - "{{ .Values.deployment.host }}"
{{- end }}
