FROM docker.io/amazon/aws-cli

WORKDIR /aws

RUN curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.29.3/2024-04-19/bin/linux/amd64/kubectl && \
    chmod +x ./kubectl && \
    
COPY ./script.sh .

RUN chmod +x ./script.sh

CMD ./script
    
