---
- name: Remove System on RedHat Insights
  block:
    - include_vars: api_credentials.yml

    - name: Get System ID from Red Hat Insights
      uri:
        url: '{{ insights_api_url }}/inventory/v1/hosts?hostname_or_id={{ fqdn }}'
        method: GET
        user: '{{ api_insights_username }}'
        password: '{{ api_insights_password }}'
        force_basic_auth: yes
        validate_certs: no
      register: uri_output

    - debug:
        msg: "Host {{fqdn}} will be removed from inventory"
      when: uri_output.json.results[0].id is defined

    - name: Purge/unregister from Red Hat Insights
      uri:
        url: '{{ insights_api_url }}/inventory/v1/hosts/{{ uri_output.json.results[0].id }}'
        method: DELETE
        user: '{{ api_insights_username }}'
        password: '{{ api_insights_password }}'
        force_basic_auth: yes
        validate_certs: no
      when: uri_output.json.results[0].id is defined
 
    - debug:
        msg: "Host {{fqdn}} not Found."
      when: uri_output.json.results[0].id is not defined
 
  when: fqdn is defined and fqdn != ''
  tags:
    - removeinsights
