apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: k8s-secret
  namespace: ns-teste-secret-store-csi
spec:
  provider: aws
  secretObjects:
    - secretName: k8s-secret
      type: Opaque
      data:
        - objectName: "username"
          key: username
        - objectName: "password"
          key: password
  parameters:
    objects: |
      - objectName: "secretmanager-teste-dev"
        objectType: "secretsmanager"
        jmesPath:
            - path: "username"
              objectAlias: "username"
            - path: "password"
              objectAlias: "password"
