##NAO ALTERAR!!!!!!######
#Role for ALL
- hosts: jenkins
  become: true
  environment: "{{ proxy_env }}"
  vars_files:
#FIXO
    - ans-shared-vars/aws-@@AWS_ACCOUNT_ID@@-env.yml
    - ans-shared-vars/lnx-credentials-env.yml
    - ans-shared-vars/pwd-credentials.yml
    - ans-shared-vars/lnx-certificate-env.yml
    - ans-shared-vars/lnx-proxy-env.yml
    - ans-shared-vars/lnx-user-env.yml
#FIXO
    - ans-shared-vars/lnx-jenkins-std-app.yml
  roles:
     - certificate
     - proxy
     - geerlingguy.java
     - lvm
     - linux-jenkins-std
     - user



