apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: administrators
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: Deivid.Pilla@br.experian.com
  # - kind: User
  #   apiGroup: rbac.authorization.k8s.io
  #   name: Cleber.JSantos@br.experian.com
  # - kind: User
  #   apiGroup: rbac.authorization.k8s.io
  #   name: JulioCesar.Domingues@br.experian.com
  # - kind: User
  #   apiGroup: rbac.authorization.k8s.io
  #   name: Fernanda.Ferreira@br.experian.com
  # - kind: User
  #   apiGroup: rbac.authorization.k8s.io
  #   name: Felipe.Navalho@br.experian.com
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
