---
- hosts: localhost
  gather_facts: yes
  become: yes
  tasks:
    - name: copi files  fazer vua cli
      ignore_errors: yes
      become: yes         
      shell: '{{item}}'
      #      no_log: yes
      with_items:
        - 'rm -rf /home/{{new_user}}/.saml2aws'
        - 'cp -r /home/svi4808-a/.tmux.conf /home/{{new_user}}'
        - 'cp -r /home/svi4808-a/repo_kp/ /home/{{new_user}}'
        - 'cp /home/svi4808-a/key_cod_nike_automation /home/{{new_user}}/'
        - 'cp /home/svi4808-a/McAfee.pem /home/{{new_user}}/'
        - 'cp /home/svi4808-a/set_eks.sh /home/{{new_user}}/'
        - 'cp /home/svi4808-a/accesstoSaml2Aws.sh /home/{{new_user}}/'
        - 'cp /home/svi4808-a/.saml2aws /home/{{new_user}}/'
        - 'cp /home/svi4808-a/sre-suport.pem /home/{{new_user}}/'
        - "sed -i 's/alessandro.bahia/{{prefix_mail}}/g' /home/{{new_user}}/.saml2aws"
        - 'chown -R {{new_user}}. /home/{{new_user}}/'

    - name: line in file  /etc/sudoers.d/{{new_user}}
      become: yes         
      lineinfile:
        path: '/etc/sudoers.d/{{new_user}}'
        line: '{{new_user}} ALL=(ALL) NOPASSWD: ALL'
        state: present
        create: true

    - name: line in file  /home/{{new_user}}/.bash_profile
      become: yes         
      lineinfile:
        path: '/home/{{new_user}}/.bash_profile'
        line: '{{item}}' 
        state: present
        create: true
      with_items:
        - 'export https_proxy=http://spobrproxy.serasa.intranet:3128'
        - 'export http_proxy=http://spobrproxy.serasa.intranet:3128'

    - name: line in file  /home/{{new_user}}/.bashrc
      become: yes         
      lineinfile:
        path: '/home/{{new_user}}/.bashrc'
        line: "alias vai='ssh -q -i ~/sre-suport.pem -o ConnectTimeout=3 -o StrictHostKeyChecking=no'"
        state: present
        create: true

    - name: running commands to execute ansible
      become: yes
      become_user: '{{new_user}}'
      environment:
          https_proxy: 'http://spobrproxy.serasa.intranet:3128'
          http_proxy: 'http://spobrproxy.serasa.intranet:3128'
      shell: '{{item}}'
      with_items:
        - 'git config --global http.sslVerify false' 
        - 'python3.11 -m ensurepip --default-pip'
        - 'python3.11 -m pip install awscli --upgrade'
        - 'python3.11 -m pip install jmespath'
        - 'python3.11 -m pip install boto3'
        - 'python3.11 -m pip install botocore'
        - 'ansible-galaxy collection install community.general --force'
        - 'ansible-galaxy collection install community.aws --force'
        - 'ansible-galaxy collection install ansible.posix --force'
        - 'ansible-galaxy collection install kubernetes.core --force'
        - 'python3.11 -m pip install xlsx2csv'
