---
- hosts: localhost
  gather_facts: no
  environment:
    https_proxy: 'http://spobrproxy.serasa.intranet:3128'
    http_proxy: 'http://spobrproxy.serasa.intranet:3128'
    AWS_REGION: sa-east-1  
  become: yes
  tasks:
    - include_role:
        name: aws
        tasks_from: sts_connection

    - include_role:
        name: aws
        tasks_from: s3_server_acces_loggin_enable.yml
 ### SDG ###
