---
- hosts: localhost
  gather_facts: no
  environment:
    https_proxy: 'http://spobrproxy.serasa.intranet:3128'
    http_proxy: 'http://spobrproxy.serasa.intranet:3128'
    AWS_REGION: sa-east-1
  become: yes
  tasks:
    - name: get connection
      import_role:
        name: aws
        tasks_from: sts_connection.yml

    - set_fact:
        sg_name: default

    - name: get sg_id
      import_role:
        name: aws
        tasks_from: ec2_security_group_get_sg_id.yml




    - name: 
      block:
        - name: get sg rules_list
          import_role:
            name: aws
            tasks_from: ec2_security_group_list_rules.yml
    
        - debug:
            var: rules_fields

        - name:
          include_tasks: roles/aws/tasks/ec2_security_group_delete_rule.yml
          loop: '{{rules_fields}}'
          loop_control:
            loop_var: rule

#        - import_role:
#            name: aws
#            tasks_from: ec2_security_group_delete_ingress.yml
#    
#        - import_role:
#            name: aws
#            tasks_from: ec2_security_group_delete_egress.yml 

      when: sg_id is defined
    


