- hosts: localhost
  gather_facts: no
  environment:
    https_proxy: 'http://spobrproxy.serasa.intranet:3128'
    http_proxy: 'http://spobrproxy.serasa.intranet:3128'
    AWS_REGION: sa-east-1
  tasks:
    - name: block check name_role and name_policy
      block:
        - name:
          include_tasks: check_token_time.yml

        - debug:
            var: connection


        - name: call connection
          import_role:
            name: aws
            tasks_from: iam_role_create_BuRoleForSreAutomation.yml


      when: account is defined and account_id is defined


    - name:  when variable is not defined
      debug: 
        msg: 
          - '##############################################'
          - '##############################################'
          - '##    definition of mandatory variables     ##'
          - '##                                          ##'                
          - '##  account                                 ##'                
          - '##  account_id                              ##'                
          - '##                                          ##'                
          - '##############################################'
          - '##############################################'

      when: account is not defined or account_id is not defined

