---
- name: include role to load sts accounts
  include_role:
    name: aws
    tasks_from: sts_connection.yml

- name: show current default config to set
  debug:
    msg:
      - "############################################################@############################################################"
      - "############################################################@############################################################"
      - "############################################################@############################################################"
      - "#                                                                                                                       #"  
      - "#                                                    SET DEFAULT TAGS                                                   #"
      - "#                                                       {{account}}                                          "
      - "#                                                                                                                       #"  
      - "############################################################@############################################################"
      - "############################################################@############################################################"
      - "############################################################@############################################################"

- name: include task aws_set_default_tag.yml to account {{account}}
  include_tasks: aws_set_default_configs_tag.yml

- name: show current default config to set
  debug:
    msg:
      - "############################################################@############################################################"
      - "############################################################@############################################################"
      - "############################################################@############################################################"
      - "#                                                                                                                       #"  
      - "#                                          SET DEFAULT kms_enable_key_rotation                                          #"
      - "#                                                       {{account}}                                                    "
      - "#                                                                                                                       #"  
      - "############################################################@############################################################"
      - "############################################################@############################################################"
      - "############################################################@############################################################"

- name: include task aws_kms_enable_key_rotation.yml to enable kms rotation
  include_tasks: aws_kms_enable_key_rotation.yml


  ###SDG###
