---
- hosts: localhost
  gather_facts: no
  tasks:
    - import_role:
        name: aws
        tasks_from: sts_connection.yml

    - import_role:
        name: aws
        tasks_from: bucket_create.yml
