---
- hosts: localhost
  gather_facts: no
  environment:
    https_proxy: 'http://spobrproxy.serasa.intranet:3128'
    http_proxy: 'http://spobrproxy.serasa.intranet:3128'
    AWS_REGION: sa-east-1
  tasks:
    - include_tasks: aws_iam_user_check_key.yml
      with_items: '{{accounts}}'
      loop_control: 
        loop_var: account      
### SDG ###
