---
- hosts: spobrnikeworker
  gather_facts: no
  environment:
    https_proxy: 'http://spobrproxy.serasa.intranet:3128'
    http_proxy: 'http://spobrproxy.serasa.intranet:3128'
    AWS_REGION: sa-east-1
  tasks:
     - name:
       include_tasks: check_detour.yml
       with_items: 
        - '{{accounts}}'
       loop_control:
         loop_var: account





