---
- hosts: localhost
  gather_facts: no
  environment:
    https_proxy: 'http://spobrproxy.serasa.intranet:3128'
    http_proxy: 'http://spobrproxy.serasa.intranet:3128'
    AWS_REGION: sa-east-1
  become: yes
  tasks:
    - name: include task to call set ak sk role-task
      include_tasks: aws_ecr_list_repository.yml
      #      with_items:
      #        - dsprod
      #          #        - '{{accounts}}'
      #      loop_control:
      #        loop_var: account

                  
