---
- hosts: localhost
  gather_facts: no 
  environment:
    https_proxy: 'http://spobrproxy.serasa.intranet:3128'
    http_proxy: 'http://spobrproxy.serasa.intranet:3128'
    AWS_REGION: sa-east-1
  tasks:
    - name: include task to call grype images
      include_tasks: grype_all_cluster.yml 
      with_items:
        - arcsandbox
                #        - '{{accounts}}'
      loop_control:
        loop_var: account

###SDG###        
