---
- hosts: localhost
  gather_facts: no
  environment:
    https_proxy: 'http://spobrproxy.serasa.intranet:3128'
    http_proxy: 'http://spobrproxy.serasa.intranet:3128'
    AWS_REGION: sa-east-1
  tasks:
    - name: create inventory loop
       include_tasks: aws_resources_inventory.yml 
      with_items:
        - '{{accounts}}'
      loop_control:
        - loop_var: account
    
    
