---
- hosts: localhost
  gather_facts: no
  environment:
    https_proxy: 'http://spobrproxy.serasa.intranet:3128'
    http_proxy: 'http://spobrproxy.serasa.intranet:3128'
    AWS_REGION: sa-east-1
  become: yes
  tasks:
    - name: Call on_board_coockitp_eks.yml
      include_tasks: on_board_coockitp_eks.yml
      loop: "{{contas}}"
      loop_control: 
        loop_var: account
