---
- hosts: localhost
  gather_facts: no
  environment:
    https_proxy: 'http://spobrproxy.serasa.intranet:3128'
    http_proxy: 'http://spobrproxy.serasa.intranet:3128'
    AWS_REGION: sa-east-1
  tasks:
    - include_tasks: aws_kms_enable_key_rotation.yml
      with_items:
#        - '{{accounts_no_prod}}'
        - '{{accounts}}'
      loop_control:
        loop_var: account      
 ### SDG ###
