---
- hosts: spobrnikeworker
  gather_facts: no
  environment:
    https_proxy: 'http://spobrproxy.serasa.intranet:3128'
    http_proxy: 'http://spobrproxy.serasa.intranet:3128'
    AWS_REGION: sa-east-1
  become: yes
  tasks:
    - name: guarantees  packages
      include_tasks: roles/pip/tasks/install_package.yml
      with_items:
        - boto3
        - argparse
        - psycopg2-binary
      loop_control:
        loop_var: pack_name
    
    - name: include task to call set ak sk role-task
      include_tasks: aws_configservice_list_discovered_resources.yml
      with_items:
        - '{{accounts}}'
      loop_control:
        loop_var: account

### SDG ###
