---
- hosts: localhost
  gather_facts: no
  environment:
    https_proxy: 'http://spobrproxy.serasa.intranet:3128'
    http_proxy: 'http://spobrproxy.serasa.intranet:3128'
    AWS_REGION: sa-east-1
  become: yes
  tasks:
    - name: include task aws_set_default_configs.yml 
      include_tasks: aws_set_default_configs.yml
      with_items:      
        - '{{accounts_no_prod}}'
      loop_control:
        loop_var: account

### SDG ###                          
