---
- hosts: '{{host}}'
  gather_facts: no
  environment:
    https_proxy: 'http://spobrproxy.serasa.intranet:3128'
    http_proxy: 'http://spobrproxy.serasa.intranet:3128'
    AWS_REGION: sa-east-1
  become: yes
  tasks:
    - import_role:
        name: config_machine      
        tasks_from: remove_pem.yml
  become: yes

###  SDG ###
