---
- hosts: localhost
  gather_facts: no
  environment:
    https_proxy: 'http://spobrproxy.serasa.intranet:3128'
    http_proxy: 'http://spobrproxy.serasa.intranet:3128'
    AWS_REGION: sa-east-1
  become: yes
  tasks:
    - name: remove existent inventory
      become: yes
      file:
        state: absent
        path: '{{item}}'
      with_items:
        - '{{inventory_eks_path}}'

    - name: include task to call aws_create_invetory_eks.yml
      include_tasks: aws_create_inventory_eks.yml
      with_items:
        - '{{accounts}}'
#        - ssrmprod
#        - reportsprod
#        - ssrmsandbox
#        - sredev

      loop_control:
        loop_var: account

### SDG ###      
                  
