---
- hosts: localhost
  gather_facts: no
  environment:
    https_proxy: 'http://spobrproxy.serasa.intranet:3128'
    http_proxy: 'http://spobrproxy.serasa.intranet:3128'
    AWS_REGION: sa-east-1
  become: yes
  tasks:
    - name: remove existent inventory
      become: yes
      file:
        state: absent
        path: '{{item}}'
      with_items:
        - '{{inventory_all_instances_path}}'

    - name: include task to call set ak sk role-task
      include_tasks: aws_create_inventory_instances.yml
      with_items:
        - '{{accounts}}'
#        - reportsdev
#        - sredev
#        - dsdev
      loop_control:
        loop_var: account

    - name: slap in the file
      become: yes
      shell: '{{item}}'
      loop:
        - " egrep 'running|eec' {{inventory_all_instances_path}} | egrep -v 'emr|EMR|node_group_on_demand_' | cut -d '|' -f2 > {{inventory_our_instance_path}}"

### SDG ######
                  
