---
- hosts: localhost
  gather_facts: no
  environment:
    https_proxy: 'http://spobrproxy.serasa.intranet:3128'
    http_proxy: 'http://spobrproxy.serasa.intranet:3128'
  tasks:
    - import_role:
        name: snow
        tasks_from: standard_change_create.yml
