---
- hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: Set host to run standalone
      add_host:
        name: '{{ item }}'
        group: hosts_invent
      with_items: '{{ hosts_list }}'


- hosts: hosts_invent 
  become: yes
  become_user: root
  gather_facts: true
  tasks:
    - import_role:
        name: zabbix
      become: yes
