#!/bin/sh
#
# Startup script for Encase
#
# chkconfig: 2345 99 05
# description: This script starts and stops Encase

# Source function library.
. /etc/rc.d/init.d/functions

# See how we were called.
PID=`ps -fe  | grep /usr/local/encase/enlinuxpc | grep -v grep | awk '{ print $2}'`
case "$1" in
  start)
	/usr/local/encase/enlinuxpc -d -p /usr/bin
	echo "Agent LISTENING"
    ;;

  stop)
    if [ "${PID}" != "" ]
    then
    	killall enlinuxpc
    fi
    ;;

  status)
    if [ "${PID}" != "" ]
    then
    	echo "Agent processes running by PID:" && echo "$PID"
    fi
    ;;

  *)
        echo "Usage: $0 {start|stop|status}"
        exit 2
esac
exit 0
