---
- name: purge old docker packages
  yum:
    name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-engine
    state: absent
    lock_timeout: 900

- name: install requirements
  yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
      - epel-release.noarch
    update_cache: yes

- name: add docker-ce repository (centos7)
  yum_repository:
    name: docker-ce
    description: Docker Repository
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    gpgkey: https://download.docker.com/linux/centos/gpg
    gpgcheck: yes
    file: docker

- name: Ansible create file with content example
  copy:
    dest: "/etc/yum.repos.d/extras.repo"
    content: |
      [extras]
      name=CentOS-$releasever - Extras
      baseurl=http://mirror.centos.org/centos/7/extras/x86_64/
      gpgcheck=0

- name: install docker-ce
  yum:
    name: docker-ce
    update_cache: yes
    enablerepo: epel,extras

- name: create docker config dir
  file:
    path: /etc/docker
    state: directory

- name: create docker daemon systemd directory
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
- name: Ansible create file with content example
  copy:
    dest: "/etc/systemd/system/docker.service.d/http-proxy.conf"
    content: |
      [Service]
      Environment="HTTP_PROXY={{ proxy_address }}"
      Environment="HTTPS_PROXY={{ proxy_address }}"
      Environment="NO_PROXY={{ docker_no_proxy }}"

- name: configure daemon.json
  blockinfile:
    path: /etc/docker/daemon.json
    create: yes
    block: |
      {
      }
- name: remove comments from file /etc/docker/daemon.json
  command: sed -i '/^[ \t]*#/d' /etc/docker/daemon.json
  become: yes