apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dragon-models
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: helm
    repoURL: https://code.experian.local/scm/cdeamlo/coe-argocd-odin-apps.git
    targetRevision: develop
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true