---
- name: set facts of path
  set_fact:
    path_over_without_deviation: /home/Check/Vul/NIKE-Vulnerability_over_without_deviation.csv
    path_over_with_deviation: /home/Check/Vul/NIKE-Vulnerability_over_with_deviation.csv
    path_persistent_vulnera: /home/Check/Vul/persistent_vulnera.csv
    path_new_vulnerability: /home/Check/Vul/New_vulnera.csv

- name: Check vulnerability over without deviation
  no_log: true
  ignore_errors: yes
#  community.general.mssql_script:
#    login_user: "{{ sqluser }}"
#    login_password: "{{ sqlpasswd }}"
#    login_host: "{{ mssql_host }}"
#    login_port: "{{ mssql_port }}"
#    db: CM_SS1_Report
#    script: "use CM_SS1_Report ; SELECT WithinSLA"
  shell: /opt/mssql-tools18/bin/sqlcmd -C -S '{{mssql_host}},{{mssql_port}}' -U '{{sqluser}}'  -P '{{sqlpasswd}}' -Q "use CM_SS1_Report ; use CM_SS1_Report ; SELECT DATEDIFF(day,(SELECT CAST(Convert(CHAR(8),(SELECT GETDATE()),112) as DATE)),(CONVERT(DATE, DueDate, 103)))as DaysUntilOverdue,DetectionHost,CVE FROM [CM_SS1_Report].[dbo].[MARSDB_BR] where VulnContactGroup like '%Nike%' and (DATEDIFF(day,(SELECT CAST(Convert(CHAR(8),(SELECT GETDATE()),112) as DATE)),(CONVERT(DATE, DueDate, 103)))) <= 20 and DeviationRequestID = '' order by DaysUntilOverdue,DetectionIP" -o '{{path_over_without_deviation}}' -W -s ";"
  register: result_without_deviation

- name: Check vulnerability over with deviation
  no_log: true
  ignore_errors: yes
  shell: /opt/mssql-tools18/bin/sqlcmd -C -S '{{mssql_host}},{{mssql_port}}' -U '{{sqluser}}'  -P '{{sqlpasswd}}' -Q "use CM_SS1_Report ; SELECT DATEDIFF(day,(SELECT CAST(Convert(CHAR(8),(SELECT GETDATE()),112) as DATE)),(CONVERT(DATE, DueDate, 103)))as DaysUntilOverdue,DaysUntilDeviationEnd,DetectionHost,CVE,ScanResult,Solution,OS FROM [CM_SS1_Report].[dbo].[MARSDB_BR] where VulnContactGroup like '%Nike%' and (DATEDIFF(day,(SELECT CAST(Convert(CHAR(8),(SELECT GETDATE()),112) as DATE)),(CONVERT(DATE, DueDate, 103)))) <= 20 and DeviationRequestID != '' order by DaysUntilDeviationEnd,DetectionIP" -o '{{path_over_with_deviation}}' -W -s ";"


- name: create loop to check with {{path_persistent_vulnera}}
  shell: egrep -v "CM_SS1_Report|----|DaysUntilOverdue|affected" '{{path_over_without_deviation}}'
  register: loop_compar

- name: debug var loop_compar
  debug:
    var: loop_compar.stdout_lines

- include_vars: roles/aws/vars/main.yml

- name: clean vulnerabilidades table from postgre
  no_log: true
  shell: export PGPASSWORD='{{pgs_pw}}';/usr/bin/psql  -h '{{pgs_host}}' -p 5432 -U '{{pgs_login}}' -d inventario -c "delete from vulnerabilidades";unset PGPASSWORD

- name: write in vulnerabilidades table from postgre
  no_log: true
  shell: export PGPASSWORD='{{pgs_pw}}';/usr/bin/psql  -h '{{pgs_host}}' -p 5432 -U '{{pgs_login}}' -d inventario -c "insert into vulnerabilidades (days_until_overdue,detection_host,cve) values ( '{{ item.split(';')[0]}}', '{{item.split(';')[1]}}','{{item.split(';')[2]}}' )";unset PGPASSWORD
  loop: "{{ loop_compar.stdout_lines }}"


- name: include task to compare diff between {{path_over_without_deviation}} and {{path_persistent_vulnera}}
  include_tasks: compare_diff.yml 
  with_items:
    - '{{loop_compar.stdout_lines}}'

- name: update file {{path_persistent_vulnera}}
  shell: cat {{path_over_without_deviation}} > {{path_persistent_vulnera}}  

- name: get number vulnerability without deviation
  shell: egrep -v "CM_SS1_Report|----|DaysUntilOverdue|affected" '{{path_over_without_deviation}}' |sed '/^\s*$/d' | wc -l  
  register: number_without_deviation

- name: get number new vulnerability
  shell: egrep -v "CM_SS1_Report|----|DaysUntilOverdue|affected" '{{path_new_vulnerability}}' |sed '/^\s*$/d' | wc -l  
  register: number_new

- name: get number vulnerability with deviation
  shell: egrep -v "CM_SS1_Report|----|DaysUntilOverdue|affected" '{{path_over_with_deviation}}' |sed '/^\s*$/d' | wc -l  
  register: number_with_deviation






- name: send email block
  block:
#    - shell: cat '{{path_file}}'
#      register: CSVData
#      
#    - set_fact:
#        sout: "{{CSVData.stdout|replace('\n','</tr><tr><td>')|replace('|','</td><td>')|replace('[','<tr><td>')|replace(']','')}}"

#    - debug:
#        var: sout
  
    - name: set fact to send email check Vulnerability
      set_fact:
        email_title: "Nike Vulnerability Detected<br/>"
        sub_title: 'This is an automatic process from Nike Program'
        description: 'check DaysUntilOverdue <= 20'
        report_date: "{{ lookup('pipe', 'date -d \"3 hour ago\" +\"%Y-%m-%d %H:%M:%S\"') }}"
        body: "<br>Process Name: Nike Vulnerability Detected<br/>
               Number of new vulnerabilitys without deviation, DaysUntilOverdue <= 20..: {{number_new.stdout}}  <br/>
               Number Vulnerabilitys without deviation, DaysUntilOverdue <= 20.........: {{number_without_deviation.stdout}} <br/>
               Number Vulnerabilitys wit deviation, DaysUntilOverdue     <= 20.........: {{number_with_deviation.stdout}} <br/>
              "
#               Vulnerability List: <br/>
#                {{sout}} "
#               {{CSVData.stdout|replace('\n','<br/>')|replace('[','')|replace(']','')}}"

    - name: send email
      become: false
      #      delegate_to: "{{workerexec}}"
      ignore_errors: yes
      mail:
        host: '{{mail_host}}'
        port: '{{mail_port}}'
        from: '{{mail_from}}'
        to:
          - '{{suport_email}}'
            #          - 'alessandro.bahia@br.experian.com'
        subject: 'Nike Vulnerability Detected'
        subtype: html
        body: "{{ lookup('template', '{{mail_template}}') }}"
        attach:
          - '{{path_over_with_deviation}}'
          - '{{path_over_without_deviation}}'
          - '{{path_new_vulnerability}}'

     

    - name: Erase files
      file:
        path: '{{item}}'
        state: absent
      with_items:
        - '{{path_over_with_deviation}}'
        - '{{path_over_without_deviation}}'
        - '{{path_new_vulnerability}}'
 
  when: number_new.stdout != ''

