package br.com.experian.model;

class PiaasMainInfo {
    String name_application;
    String name;
    String product;
    String framework;
    String version_application;
    String language_application;
    String author;
    String author_email;
    String environment_deploy;
    String type_deploy;
    String repository;
    String type_application;
    String gearr_id;
    String gearr_application_name;
    String gearr_score;
    String gearr_u_network_type;
    String gearr_analysis_performed = "false";
    String business_service;
    String assignment_group_application;
    String tribe;
    String squad;
    String date_execution_start;
    String date_execution_end;
    String sonarqube_score;
    String sonarqube_url;
    String sonarqube_new_security_rating;
    String sonarqube_new_reliability_rating;
    String sonarqube_new_maintainability_rating;
    String sonarqube_critical_violations;
    String sonarqube_blocker_violations;
    String sonarqube_analysis_performed = "false";
    String veracode_score;
    String veracode_id;
    String veracode_url;
    String veracode_sca_violate_policy;
    String veracode_analysis_performed = "false";
    String performace_score;
    String performace_url;
    String performace_analysis_performed = "false";
    String qs_test_score;
    String qs_test_url;
    String qs_test_analysis_performed = "false";
    String sdelement_score;
    String sdelement_tasks;
    String sdelement_tasks_complete;
    String sdelement_analysis_performed = "false";
    String pentest_score;
    String pentest_analysis_performed = "false";
    String waf_score;
    String waf_analysis_performed = "false";
    String delivery_reliability_performed = "false"
    String score;
    String change_order;
    String pipeline_code_execution;
    String pipeline_status;
    String pipeline_code_error;
    String gearr_dependencies;
    String books;
    String jira_key;
    String cmdb_dependencies;
    String jdk;
    String incident_number;
    String change_order_planned_start;
    String change_order_planned_end;
    String change_order_work_start;
    String change_order_work_end;
    String incident_p1p2;
    String author_opened;
    String author_email_opened;
    String author_data_opened;
    String author_approved;
    String author_email_approved;
    String author_data_approved;
    String gearr_business_criticality;
    String psa_project_name;
    String psa_project_id;
    String psa_project_status;
    String psa_go_live_date;
    String psa_significant_change;
    String seds_setup = "false";
    String seds_thema = "false";
    String seds_thema_false_positive = "false";
    String mav_room_configured = "false";
    String lead_time_created;
    String lead_time_closed;
    String problem_score;
    String problem_analysis_performed = "false";
    String handover_score;
    String handover_analysis_performed = "false";
    String handover_items;
    String container_vulnerability = "false";
    String container_vulnerability_analysis_performed = "false";
    String eks_policy_score;
    Boolean dependguard = false;
    Boolean error_budget_configured = false;
    String author_title;
    String deployment_strategy;
    String SedsBasicButtonModule = "false";
    String SedsFabButtonModule = "false";
    String SedsFlatButtonModule = "false";
    String SedsGroupButtonsModule = "false";
    String SedsOutlinedButtonModule = "false";
    String SedsAvatarModule = "false";
    String SedsBadgeModule = "false";
    String SedsCheckboxModule = "false";
    String SedsFormFieldTextModule = "false";
    String SedsFormFieldTextareaModule = "false";
    String SedsHeaderModule = "false";
    String SedsIconModule = "false";
    String SedsTimerModule = "false";
    String SedsAccordionModule = "false";
    String SedsAlertBasicModule = "false";
    String SedsAlertLegallyRestrictedDataModule = "false";
    String SedsAlertServiceUnavailableModule = "false";
    String SedsAlertUnderageRestrictedDataModule = "false";
    String SedsBreadcrumbModule = "false";
    String SedsCardModule = "false";
    String SedsFormFieldDropdownModule = "false";
    String SedsFormFieldNumberModule = "false";
    String SedsFooterModule = "false";
    String SedsLoadersBarModule = "false";
    String SedsLoadersBrandModule = "false";
    String SedsLoadersSpinnerModule = "false";
    String SedsMegaButtonModule = "false";
    String SedsModalModule = "false";
    String SedsModalBlockedAccessModule = "false";
    String SedsModalEndedSessionModule = "false";
    String SedsModalExpiredSessionModule = "false";
    String SedsModalLegallyRestrictedDataModule = "false";
    String SedsModalServiceUnavailableModule = "false";
    String SedsModalSessionWillExpireModule = "false";
    String SedsModalUnderageRestrictedDataModule = "false";
    String SedsNotFoundComponent = "false";
    String SedsNotFoundModule = "false";
    String SedsPaginatorModule = "false";
    String SedsPopoverModule = "false";
    String SedsRadioButtonModule = "false";
    String SedsSliderModule = "false";
    String SedsSearchModule = "false";
    String SedsSnackbarModule = "false";
    String SedsSwitchModule = "false";
    String SedsTableModule = "false";
    String SedsTagsModule = "false";
    String SedsTokensModule = "false";
    String SedsTimelineModule = "false";
    String SedsTooltipModule = "false";
    String SedsFormFieldAutocompleteModule = "false";
    String SedsStepperModule = "false";
    String SedsDatepickerModule = "false";
    String SedsHeaderLogoModule = "false";
    String SedsHeaderMenuModule = "false";
    String SedsHeaderUserModule = "false";
    String SedsModalUnauthorizedAccessModule = "false";
    String SedsTabsModule = "false";

}
return new PiaasMainInfo()
