[all]
spobrsndk8s1 ansible_host=10.99.145.120 ansible_user=ansible
spobrsndk8s2 ansible_host=10.99.145.175 ansible_user=ansible
spobrsndk8s3 ansible_host=10.99.145.50 ansible_user=ansible
[kube-master]
spobrsndk8s1
spobrsndk8s2
spobrsndk8s3
[etcd]
spobrsndk8s1
spobrsndk8s2
spobrsndk8s3
[kube-node]
spobrsndk8s1
spobrsndk8s2
spobrsndk8s3
[k8s-cluster:children]
kube-master
kube-node
