- name: Add Logstash logstash.yml file.
  template:
    src: logstash.yml.j2
    dest: /etc/logstash/logstash.yml
    mode: 0644

- name: Add Logstash pipelines.yml file.
  template:
    src: pipelines.yml.j2
    dest: /etc/logstash/pipelines.yml
    mode: 0644