controller:
  nodeSelector:
    Worker: infra
  tolerations:
  - effect: NoSchedule
    key: dedicated
    operator: Equal
    value: infra
  - effect: NoSchedule
    key: Disabled
    operator: Equal
    value: ForKarpenter
hostNetwork: true
image:
  repository: {{account_id}}.dkr.ecr.sa-east-1.amazonaws.com/chainguard/aws-efs-csi-driver
  tag: "v2.0.4-r1"
sidecars:
  csiProvisioner:
    image:
      repository: {{account_id}}.dkr.ecr.sa-east-1.amazonaws.com/chainguard/kubernetes-csi-external-provisioner
      tag: "v5.0.1"  
  livenessProbe:
    image:
      repository: {{account_id}}.dkr.ecr.sa-east-1.amazonaws.com/chainguard/kubernetes-csi-livenessprobe
      tag: "v2.13.0"
  nodeDriverRegistrar:
    image:
      repository: {{account_id}}.dkr.ecr.sa-east-1.amazonaws.com/chainguard/kubernetes-csi-node-driver-registrar
      tag: "v2.11.0"
storageClasses:
- name: efs
  parameters:
    basePath: /dynamic_provisioning
    directoryPerms: "700"
    fileSystemId: {{cluster_fs_id}}
    gidRangeEnd: "2000"
    gidRangeStart: "1000"
    provisioningMode: efs-ap
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
useFips: true

