apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: servicecatalog
spec:
  disruption:
    budgets:
      - nodes: 10%
      - schedule: "0 8 * * mon-fri"
        duration: 14h
        nodes: "0"
    consolidationPolicy: WhenUnderutilized
    expireAfter: 168h
  limits:
    cpu: '256'
    memory: 512Gi
  template:
    spec:
      kubelet:
        maxPods: 256
      nodeClassRef:
        name: servicecatalog
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: ["c", "m", "r", "t"]
        - key: karpenter.k8s.aws/instance-hypervisor
          operator: In
          values: ["nitro"]
        - key: karpenter.k8s.aws/instance-cpu
          operator: In
          values: ["4", "8", "16"]
      startupTaints: []
      taints: []
  weight: 10
---
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: servicecatalog-spot
spec:
  disruption:
    budgets:
      - nodes: 10%
      - schedule: "0 8 * * mon-fri"
        duration: 14h
        nodes: "0"
    consolidationPolicy: WhenUnderutilized
    expireAfter: 168h
  limits:
    cpu: '256'
    memory: 512Gi
  template:
    metadata:
      labels:
        Spot: "true"
    spec:
      kubelet:
        maxPods: 256
      nodeClassRef:
        name: servicecatalog
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot"]
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: ["c", "m", "r", "t"]
        - key: karpenter.k8s.aws/instance-hypervisor
          operator: In
          values: ["nitro"]
        - key: karpenter.k8s.aws/instance-cpu
          operator: In
          values: ["4", "8", "16"]
      startupTaints: []
      taints:
        - key: dedicated
          value: spot
          effect: NoSchedule
  weight: 20