---
- set_fact:
    domain: '{{ ansible_domain }}'

- name: Set definitions of Experian domain
  set_fact:
    config: '{{ centrify_experian }}'
  when: domain == 'br.experian.local'

- name: Set definitions of Serasa domain
  set_fact:
    config: '{{ centrify_serasa }}'
  when: domain == 'serasacliente.com.br'

- name: Copy Kerberos conf
  copy:
    src: files/{{ config.krb5_config }}
    dest: /etc/krb5.conf

- name: Permissions
  file:
    path: /etc/krb5.conf
    owner: root
    group: root
    mode: 0644

- shell: adreload
  ignore_errors: yes
  args:
    executable: /bin/bash
