coe_argocd:
  env: "prod"
  project_name: "coe-data-platform"
  eks_cluster_name: "coe-data-platform-01"
  domain: "dev-mlops.br.experian.eeca"
  # Name of the AWS Secrects Manager
  secretsManager: "coe-data-platform/coe-data-platform-01/dex_prod-settings"

  istio:
    enabled: true
    gateway:
      selector: "ingress"
      port:
        name: "http"
        number: "8080"
        protocol: "HTTP"
argo-cd:
  fullnameOverride: "argocd"
  dex:
    enabled: false
  server:
    deploymentAnnotations:
      aws-tf-eks-timestamp: ""
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: "arn:aws:iam::837714169011:role/BURoleForDeployAccessSecretsManager"
    volumeMounts:
      - name: "argocd-repositories"
        mountPath: "/mnt/argocd-repositories"
        readOnly: true
    volumes:
      - name: "argocd-repositories"
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "argocd-repositories"
  global:
    image:
      repository: 837714169011.dkr.ecr.sa-east-1.amazonaws.com/argocd
      tag: "v2.8.4"
  configs:
    cm:
      url: "https://deploy-coe-data-platform-01-prod.corp-data.br.experian.eeca"
      oidc.config: |-
        name: internalcluster
        issuer: https://auth-coe-odin-01-dev.dev-mlops.br.experian.eeca/api/dex/
        clientID: argo-cd
        clientSecret: PUT_YOUR_SECRET_HERE
        requestedScopes: 
          - openid
          - profile
          - email
          - groups
    params:
      server.insecure: true
      server.dex.server: "http://dex.auth-system:5556"
    rbac:
      policy.default: "role:readonly"
      policy.csv: |
        g, aws-mlops-odin-Argocd-dev-admin, role:admin
    ssh:
      knownHosts: |
        code.experian.local ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCSFF3tE6OdnmmsC+PxL+7v8S80ZG1mnz6XEmeZQpZAiDFx4OmVjBPbQevWyyTpkjKPtv+zJWjFuaeOGAi//G+tDjQylpXQ1lNlnH6Msh3+MTS30EeyGyLhskNJoq6dnsbjTcT0eG5EqQRZ7TK6Rtx+xBNngu+jefa3o+XrWGrEElKuOgPMIH1jQaxVHrSvEorD0mGf0AA2ggGW85eFqS3ZrFqc4byR+Hh4lBqM2ls+YzhHJo/X70dZkfPV7inkYDhlQiM+rdPbboWiA3yDna1vLKOEs8aDQ0Xwv+TrJnh13u6gGx4lbKi3QBoVHN8RHPFuhdlpT0EPb/4Os0gOYHEd
    tls:
      certificates:
        code.experian.local: |
          -----BEGIN CERTIFICATE-----
          MIIFBTCCA+2gAwIBAgIQM0aqpcH7SutfgpFYBkV+rjANBgkqhkiG9w0BAQsFADBX
          MQswCQYDVQQGEwJVUzEWMBQGA1UEChMNRW50cnVzdCwgSW5jLjEwMC4GA1UEAxMn
          RW50cnVzdCBQcml2YXRlIFRydXN0IFNTTCBDQSAtIFByaXZTU0wxMB4XDTIxMDky
          NzE0NDgzNVoXDTIyMTAyNjE0NDgzNVowejELMAkGA1UEBhMCVVMxDjAMBgNVBAgT
          BVRleGFzMQ4wDAYDVQQHEwVBbGxlbjEtMCsGA1UEChMkRXhwZXJpYW4gSW5mb3Jt
          YXRpb24gU29sdXRpb25zLCBJbmMuMRwwGgYDVQQDExNjb2RlLmV4cGVyaWFuLmxv
          Y2FsMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAu/JSaISK2+HBt8lb
          zgn8h2VcKNaKyljR//f0ez5FrKbVVkbgIQBsIGwXYkOEEGyfXZZ94dfkjTOz409Q
          UjatNelh6SbwsJx3M3cscgmFHC65EBq6dy8vMETbMEfg2HXvZluMByf59UHvdcen
          xHyviZAwLAcQQOBl2AtqmIGs/3zv207WcXJ1ViixDw5gycy8OuiJEuNj1yfcM60v
          TWLMmuPJ7kS6EVCbk4hJWCcuwttuJ3SNQyVHf9FXNQcKwkuk6cbZsaFAe7dVnjZX
          tX+zXk/sEd37kAyyQ2KMr9gQLNJAB0e5uDV2tDO7BcnkR0Q0VZQYTWMlxHVFiZir
          gUTw6wIDAQABo4IBqDCCAaQwDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQUnq5QJU16
          pGb6LHgOwwRCak0RE84wHwYDVR0jBBgwFoAUYyZrlTDBqCAQgzJRYiliYtt+pNcw
          agYIKwYBBQUHAQEEXjBcMCMGCCsGAQUFBzABhhdodHRwOi8vb2NzcC5lbnRydXN0
          Lm5ldDA1BggrBgEFBQcwAoYpaHR0cDovL2FpYS5lbnRydXN0Lm5ldC9wcml2c3Ns
          MS1jaGFpbi5jZXIwNAYDVR0fBC0wKzApoCegJYYjaHR0cDovL2NybC5lbnRydXN0
          Lm5ldC9wcml2c3NsMS5jcmwwPgYDVR0RBDcwNYITY29kZS5leHBlcmlhbi5sb2Nh
          bIIeYml0YnVja2V0Z2xvYmFsLmV4cGVyaWFuLmxvY2FsMA4GA1UdDwEB/wQEAwIF
          oDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwQwYDVR0gBDwwOjA4Bgtg
          hkgBhvpsCgEJATApMCcGCCsGAQUFBwIBFhtodHRwczovL3d3dy5lbnRydXN0Lm5l
          dC9ycGEwDQYJKoZIhvcNAQELBQADggEBABvNdaHosj+1lNOfyLpW+iZVM8t/sToM
          J4kDXuLw6JrBzSVVf0YDK6N+8K9/w93ttQDg3KeD8hvWzddCTb7pbUfXOqmUci3l
          ylALRUip4Fj89ycldUfXCqWxdOXzy3XJeTsSpLjPigicU5AkwbGhCdzQEH3e2uqQ
          uemYDHVZJKbW9eVkhQxdbr2Qgvm8tS9sjN3xtZCORTYP2qDk70d4HVOSl2RCRA3u
          0iKDuZonDaPcoBA7CX5sYaqqM5lOQIEzK9Csv+M+xP7VSSh+tMMGl/5LHZhsiCA6
          x+5VWkUxvAoh1ROveRWi4AqJ9CXr8DC7xBIkaFFhqkYlLlkf6VkATbA=
          -----END CERTIFICATE-----
          -----BEGIN CERTIFICATE-----
          MIIE1TCCA72gAwIBAgIQUa6r9070qthABWKqwb+uQTANBgkqhkiG9w0BAQsFADCB
          vjELMAkGA1UEBhMCVVMxFjAUBgNVBAoTDUVudHJ1c3QsIEluYy4xKDAmBgNVBAsT
          H1NlZSB3d3cuZW50cnVzdC5uZXQvbGVnYWwtdGVybXMxOTA3BgNVBAsTMChjKSAy
          MDEyIEVudHJ1c3QsIEluYy4gLSBmb3IgYXV0aG9yaXplZCB1c2Ugb25seTEyMDAG
          A1UEAxMpRW50cnVzdCBSb290IENlcnRpZmljYXRpb24gQXV0aG9yaXR5IC0gRzMw
          HhcNMjEwNzI4MDAwMDAwWhcNMzAxMjE4MDAwMDAwWjBXMQswCQYDVQQGEwJVUzEW
          MBQGA1UEChMNRW50cnVzdCwgSW5jLjEwMC4GA1UEAxMnRW50cnVzdCBQcml2YXRl
          IFRydXN0IFNTTCBDQSAtIFByaXZTU0wxMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A
          MIIBCgKCAQEAqyoRBJq7QaI4qvj6wfdEW6J0qXpz9bKroNMpnevw1YRS4gOd+R6z
          c3VAAUuk26425zFMR+2XpAfHVVN5aC8avzKDyjrnQ0EVNXNZ2fgPj3/kQcwMQwWp
          r57VvM7i8UByn4ve5z2dJK/RrjIYSAu0P4O2r6f/F/sRzVaHqv40s2gB798JhgOJ
          bJ7jHZmJYYMCXA2++5KabQQgycFHraR3jpujxD1I3axs8Hz3npIl7CnXjDAy1FDo
          dvZH/SWqsQ7QTbjHPkzqE2UYfQ+FNGCroTSXL6FWv54k4Y71oFbsh8IY0Duqyz83
          T3LGn609LhlnvKLPEA/oF1q63CBWNcqePwIDAQABo4IBMzCCAS8wEgYDVR0TAQH/
          BAgwBgEB/wIBADAdBgNVHQ4EFgQUYyZrlTDBqCAQgzJRYiliYtt+pNcwHwYDVR0j
          BBgwFoAUtXUB7kHHyno/8vxaVsd2BgsGbGYwMwYIKwYBBQUHAQEEJzAlMCMGCCsG
          AQUFBzABhhdodHRwOi8vb2NzcC5lbnRydXN0Lm5ldDAwBgNVHR8EKTAnMCWgI6Ah
          hh9odHRwOi8vY3JsLmVudHJ1c3QubmV0L2czY2EuY3JsMA4GA1UdDwEB/wQEAwIB
          hjAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwQwYDVR0gBDwwOjA4Bgtg
          hkgBhvpsCgEJATApMCcGCCsGAQUFBwIBFhtodHRwczovL3d3dy5lbnRydXN0Lm5l
          dC9ycGEwDQYJKoZIhvcNAQELBQADggEBAGaVtenDla0d2MKLCkvJJJ74f5HtC015
          qSRkbGS+IArXJiZFeppw9acBYOV49YWpOnNNY9Xk8V+w1N98hArlmrU6eh8eou1j
          SnxccI3Z2TgYATH7DaKDw76vgztj6uc9WR0xprb4zy4nSi9hXj8lPLeKAs41D193
          RJgbCZ4NJ5+gnR26tdPShSrKVp898iwtRfAesYm3J1t80vsOOIdpZgoLnTtl8DK/
          YdDt6YekT0j/CJfpMzGyVFt/F3hsKbWj2feuK+XS66PzZqr7vvt0NXD2pgc/kk4c
          ocrpAeDeN2jX923sozn8c24B17EkN/r1BQtjZ3tcJnelBmDqnkgPt7U=
          -----END CERTIFICATE-----
          -----BEGIN CERTIFICATE-----
          MIIERzCCAy+gAwIBAgINAMK7Y+oAAAAAUNC1oTANBgkqhkiG9w0BAQUFADCBvjEL
          MAkGA1UEBhMCVVMxFjAUBgNVBAoTDUVudHJ1c3QsIEluYy4xKDAmBgNVBAsTH1Nl
          ZSB3d3cuZW50cnVzdC5uZXQvbGVnYWwtdGVybXMxOTA3BgNVBAsTMChjKSAyMDEy
          IEVudHJ1c3QsIEluYy4gLSBmb3IgYXV0aG9yaXplZCB1c2Ugb25seTEyMDAGA1UE
          AxMpRW50cnVzdCBSb290IENlcnRpZmljYXRpb24gQXV0aG9yaXR5IC0gRzMwHhcN
          MTIxMjE4MTc1NzQ0WhcNMzAxMjE4MTgyNzQ0WjCBvjELMAkGA1UEBhMCVVMxFjAU
          BgNVBAoTDUVudHJ1c3QsIEluYy4xKDAmBgNVBAsTH1NlZSB3d3cuZW50cnVzdC5u
          ZXQvbGVnYWwtdGVybXMxOTA3BgNVBAsTMChjKSAyMDEyIEVudHJ1c3QsIEluYy4g
          LSBmb3IgYXV0aG9yaXplZCB1c2Ugb25seTEyMDAGA1UEAxMpRW50cnVzdCBSb290
          IENlcnRpZmljYXRpb24gQXV0aG9yaXR5IC0gRzMwggEiMA0GCSqGSIb3DQEBAQUA
          A4IBDwAwggEKAoIBAQDAt8tUqsbxBmiUfX+A4mmfEJk2xA+as/x+hekOVJv1iOZ5
          WtbMRyatdtiiVbMQBFfoSBJjevWqxOBfRdlkPmyTCWiaLD8FdZ/d69HUpsDCuzNH
          dU9OhEvOgRyX/cbOQ+4HwLyzPAc61z1Ai/B5r42F2Gf8qvFF9e/zI8sGhMCrn/sa
          APaqVRaNsblQDFY3q3ZUvtkaCP4lbUnbe0LbwSaAGM/FoqXTz+aMIb00iMmp0SHf
          ea/ETjDl76CqZ2a9df/IrfE5gKK0msWLacyl+HUtZ27lyuWCPSwDp7ipSvpMPlDj
          ZvIQG2XfQUSa8rg9P/nbIWWLWWvlHoKD6tb+P4p1AgMBAAGjQjBAMA4GA1UdDwEB
          /wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBS1dQHuQcfKej/y/FpW
          x3YGCwZsZjANBgkqhkiG9w0BAQUFAAOCAQEAv1e4TOpmwwMtcapOYidndLkyF1i0
          7O+8FSFEh9jKK8CufS7bTKFo2+W4Ku6M9xha20WIX/d74caxdBeR44vkBQZADkhC
          dvhTQvJhezF9UlXoZbRq/pRvkyOLRBuvCkX7i2cJ4/k/zD30BGPj/x7KRanOdsuB
          wG11ghvPuJ6v+3sbBaMvoF+rsdwzWioaNAOYR8AmBDp/jhaxzl+3UbIAf1IqEkrf
          4H/pnNmT9l6t6fp9C4BuD9TaSpRbhksijIO8UnuPc0ZGqJ1k82PMkb2klp+pFNEI
          KksYsjw3TtRoNWfLHaPIbw3hSudbFCQEdkXYXTfrC/etEm/SQPVfhtnfiQ==
          -----END CERTIFICATE-----

  redis:
    image:
      repository: 837714169011.dkr.ecr.sa-east-1.amazonaws.com/redis
      tag: 7.0.7-alpine
