apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: teste
spec:
  generators:
  - list:
      # Lista de clusters que irá deployar
      elements:
      - cluster: in-cluster
        url: https://kubernetes.default.svc
      - cluster: sre-cs-eks-01-sandbox
        url: https://F22B024026B89EAF57E8D4840797513E.yl4.sa-east-1.eks.amazonaws.com
      - cluster: reports-eks-01-dev
        url: https://71B3F73DE93545A8EB513D39A0697901.sk1.sa-east-1.eks.amazonaws.com
      - cluster: reports-eks-01-uat
        url: https://CE8B6382B2610F6BB45AC24158EB9BD9.yl4.sa-east-1.eks.amazonaws.com

  template:
    metadata:
      name: 'cluster-role-{{cluster}}'
    spec:
      project: default
      source:
        repoURL: ssh://git@code.experian.local/trsrecs/eks-gitops.git
        targetRevision: develop
        path: applicationset/cluster-roles/{{cluster}}
      destination:
        server: '{{url}}'
#        namespace: app-test
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true

