apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "* */15 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: argocd-job
            image: bitnami/kubectl:latest
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
