apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ include "app.fullname" . }}-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  selector:
    istio: ingress
  servers:
    - hosts:
        - "{{ include "app.fullname" . }}.{{ .Values.istio.domain }}"
      port:
        name: http
        number: 80
        protocol: HTTP
      tls:
        httpsRedirect: true
    - hosts:
        - "{{ include "app.fullname" . }}.{{ .Values.istio.domain }}"
      port:
        name: https
        number: 8080
        protocol: HTTP